import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US': {

      'You first': 'You first',
      'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals': 'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals',
      'Beautifully-designed menus' : 'Beautifully-designed menus',
      'Every menu item is manually reviewed by our team' : 'Every menu item is manually reviewed by our team',
      "Unbeatable rates":"Unbeatable rates",
      'We don’t charge any order fees. Delivery fees go where they belong.':'We don’t charge any order fees. Delivery fees go where they belong.',
      'WELCOME BACK':'WELCOME BACK',
      'Login your account.':'Login your account.',
      "Login With Mobile Number":"Login With Mobile Number",
      "Login With Email Address":"Login With Email Address",
      'Enter Mobile Number': 'Enter Mobile Number',
      'Please enter phone number': 'Please enter phone number',
      'Phone Number not register yet Please Signup' : 'Phone Number not register yet Please Signup',
      "OTP has been sent": "OTP has been sent",
      "Oops, OTP send failed": "Oops, OTP send failed",
      'Email not register yet Please Signup': 'Email not register yet Please Signup',
      'Enter your Mobile number':'Enter your Mobile number',
      'Please enter your phone number':'Please enter your phone number',
      'Please enter your email':'Please enter your email',
      'Enter a valid email address':'Enter a valid email address',
      'Please enter your otp':'Please enter your otp',
      'Enter Email' : 'Enter Email',
      'send': 'send',
      'Enter Otp':'Enter Otp',
      "OTP is verified": "OTP is verified",
      "Invalid OTP" : "Invalid OTP",
      'Login' : 'Login',
      'Customer Booking?' : 'Customer Booking?',
      'Sign in as a business': 'Sign in as a business',
      'Or Login with' : 'Or Login with',
      'Facebook': 'Facebook',
      'Google': 'Google',
      "Don't Have an Account?": "Don't Have an Account?",
      'Signup' : 'Signup',
      'Email already exits':'Email already exits',
      'Mobile Number already exits': 'Mobile Number already exits',
      "Create Account": "Create Account",
      "Enter Your Name": "Enter Your Name",
      "Please enter your name": "Please enter your name",
      'Enter your Email':'Enter your Email',
      "Valid Email is required":"Valid Email is required",
      "Email is required":"Email is required",
      "Please accept term and conditions":"Please accept term and conditions",
      "Email":"Email",
      "Mobile Number":"Mobile Number",
      'Phone Number':'Phone Number',
      'Are you agree terms and conditions?':'Are you agree terms and conditions?',
      "Already Have an Account?":"Already Have an Account?",
      "Address": "Address",
      "Location": "Location",
      'Yes I understand and agree to the': 'Yes I understand and agree to the',
      'Terms And Conditions': 'Terms And Conditions',
      'Save':'Save',
      'Sent OTP  to verify your number':'Sent OTP  to verify your number',
      'Enter the OTP Send to':'Enter the OTP Send to',
      'RESEND OTP':'RESEND OTP',
      'THANK YOU':'THANK YOU',
      'your account has been successfully created':'your account has been successfully created',
      "CONTINUE":"CONTINUE",
      'My Orders':'My Orders',
      "My Profile":"My Profile",
      "Notification":"Notification",
      "My Address":"My Address",
      "Privacy Policy":"Privacy Policy",
      'Help Center':'Help Center',
      'Log Out':'Log Out',
      "Profile":"Profile",
      'Home':'Home',
      "Find for food or restaurant...":"Find for food or restaurant...",
      'Near By':'Near By',
      'Rating':'Rating',
      "Offers":"Offers",
      "Offer":"Offer",
      "Popular":"Popular",
      'Restaurants chosen for you':'Restaurants chosen for you',
      'Explore Now':'Explore Now',
      'Popular restaurants in Madrid':'Popular restaurants in Madrid',
      "Status":"Status",
      "Complete Address":"Complete Address",
      "Choose Address":"Choose Address",
      "Enter complete address":"Enter complete address",
      "Office":"Office",
      "Hotel":"Hotel",
      "Other":"Other",
      "Flat, House no, Floor, Tower,Street":"Flat, House no, Floor, Tower,Street",
      "Street, Society, Landmark":"Street, Society, Landmark",
      'Select city':'Select city',
      "Recipient’s name":"Recipient’s name",
      'save address':'save address',
      'Address Added':'Address Added',
      "No Address Found":"No Address Found",
      "Edit":"Edit",
      "Delete":"Delete",
      "Are you sure you want to delete this Address":"Are you sure you want to delete this Address",
      "CheckOut":"CheckOut",
      'Deliver To':'Deliver To',
      "Please choose address":"Please choose address",
      'Use Coupons':'Use Coupons',
      'Applied Successfully':'Applied Successfully',
      'You saved':'You saved',
      'Subtotal':'Subtotal',
      'Tax And Fees':'Tax And Fees',
      'Delivery':'Delivery',
      'Save Coupon Code':'Save Coupon Code',
      'Total':'Total',
      'Items':'Items',
      "Payment Method":"Payment Method",
      'Debit/Credit Card':'Debit/Credit Card',
      'PayPal':'PayPal',
      "Place Order":"Place Order",
      "Cart is empty":"Cart is empty",
      "Browse":"Browse",
      "Check Order Details":"Check Order Details",
      "your reservation is confirmed":"your reservation is confirmed",
      "Your OrderId:":"Your OrderId:",
      "Delivery Orders":"Delivery Orders",
      "Active":"Active",
      "Completed":"Completed",
      "Cancelled":"Cancelled",
      "Cancel Order":"Cancel Order",
      "See Details":"See Details",
      'Empty':'Empty',
      'You do not have an active order of this time':'You do not have an active order of this time',
      "Leave Review":"Leave Review",
      "Order Again":"Order Again",
      "Time":"Time",
      "Guest":"Guest",
      "Cancel":"Cancel",
      "okay":"okay",
      "Upload images":"Upload images",
      'Dining':'Dining',
      'Please select image':'Please select image',
      'Please select booking type':'Please select booking type',
      'Select Picture from':'Select Picture from',
      'Cropper':'Cropper',
      "Camera":"Camera",
      'Gallery':'Gallery',
      'Orders':'Orders',
      'Wallet':'Wallet',
      'Order List':'Order List',
      "Filter":"Filter",
      "Yes":"Yes",
      "No":"No",
      "False":"False",
      "True":"True",
      "Search":"Search",
      "Dining Orders":"Dining Orders",
      "No User Found":"No User Found",
      "Date":"Date",
      "Name":"Name",
      'Please enter about yourself':'Please enter about yourself',
      "Upload Restaurant Images or Videos":"Upload Restaurant Images or Videos",
      "Upload Restaurant Menu Card":"Upload Restaurant Menu Card",
      'Image Gallery':'Image Gallery',
      'Choose From Gallery':'Choose From Gallery',
      "No Coupon Found":"No Coupon Found",
      "Create promo code":"Create promo code",
      "Update promo code":"Update promo code",
      'Code is Updated':'Code is Updated',
      'Code is Created':'Code is Created',
      "Promo Code Name":"Promo Code Name",
      'Please enter your Promo Code Name ':'Please enter your Promo Code Name ',
      'Sunday Code':'Sunday Code',
      'Code':'Code',
      'Happy sunday':'Happy sunday',
      'Please enter your Code ':'Please enter your Code ',
      'Please enter your Discount ':'Please enter your Discount ',
      "Max Discount":"Max Discount",
      "Start Date":"Start Date",
      'Please enter start Date ':'Please enter start Date ',
      'Select Start Date':'Select Start Date',
      "End Date":"End Date",
      'Please enter end Date ':'Please enter end Date ',
      'Select End Date':'Select End Date',
      'UPDATE COUPON':'UPDATE COUPON',
      'CREATE COUPON':'CREATE COUPON',
      'basad on 23 reviews':'basad on 23 reviews',
      'Excellent        ':'Excellent        ',
      'Good               ':'Good               ',
      'Average          ':'Average          ',
      'Below Average':'Below Average',
      "Chat/Email":"Chat/Email",
      "Resvago team":"Resvago team",
      "FAQ":"FAQ",
      'here':'here',
      "Set Delivery":"Set Delivery",
      "Cancellation":"Cancellation",
      "Menu selection":"Menu selection",
      "Preparation time":"Preparation time",
      'Please enter your preparation Time':'Please enter your preparation Time',
      '20 Mint':'20 Mint',
      "Average meal for 1 Member":"Average meal for 1 Member",
      'Please enter your average Meal For 1 Member':'Please enter your average Meal For 1 Member',
      'Submit':'Submit',
      "Please enter bank account Name":"Please enter bank account Name",
      "Bank Account Number":"Bank Account Number",
      "Please enter bank account number":"Please enter bank account number",
      "Account Holder Name":"Account Holder Name",
      "Please enter account holder name":"Please enter account holder name",
      "IFSC Code":"IFSC Code",
      "Please enter IFSC code":"Please enter IFSC code",
      "ADD ACCOUNT":"ADD ACCOUNT",
      "Order ID:":"Order ID:",
      "Orders Details":"Orders Details",
      "Selected Items":"Selected Items",
      "Qty:":"Qty:",
      "Restaurant Details":"Restaurant Details",
      "Restaurant Name":"Restaurant Name",
      "Restaurant Number":"Restaurant Number",
      "Restaurant Address":"Restaurant Address",
      "Review":"Review",
      'food quality':'food quality',
      'food quantity':'food quantity',
      'How did we do?':'How did we do?',
      'communication':'communication',
      'hygiene':'hygiene',
      "About required":"About required",
      'FeedBack':'FeedBack',
      'Skip':'Skip',
      'Restaurants':'Restaurants',
      'Layers of delicious restoring':'Layers of delicious restoring',
      'Up to \$10 Master card Cashback':'Up to \$10 Master card Cashback',
      'Use code Card Above \$120':'Use code Card Above \$120',
      'Select Date':'Select Date',
      'Menu List':'Menu List',
      'Slots not available':'Slots not available',
      'Please select slot number':'Please select slot number',
      'Please select guest number':'Please select guest number',
      'Lunch':'Lunch',
      'Dinner':'Dinner',
      'Next':'Next',
      'Number Of Guests':'Number Of Guests',
      'We have max':'We have max',
      'sitting capacity':'sitting capacity',
      'Select Your Offer':'Select Your Offer',
      'Off On “A La Carte” Menu':'Off On “A La Carte” Menu',
      'Discount available for the booked timeslot preset menus and drinks not included':'Discount available for the booked timeslot preset menus and drinks not included',
      'off':'off',
      'No Offer Selected':'No Offer Selected',
      'Restaurants Menu Chosen For You':'Restaurants Menu Chosen For You',
      'Please select menu':'Please select menu',
      'Dine In':'Dine In',


}};}

