import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          'Logout' : 'Logout',
          'Change Language': 'Change Language',
          'My Wishlist' : 'My Wishlist',
          'You first': 'You first',
          'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals':
              'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals',
          'Beautifully-designed menus': 'Beautifully-designed menus',
          'Every menu item is manually reviewed by our team':
              'Every menu item is manually reviewed by our team',
          "Unbeatable rates": "Unbeatable rates",
          'We don’t charge any order fees. Delivery fees go where they belong.':
              'We don’t charge any order fees. Delivery fees go where they belong.',
          'WELCOME BACK': 'WELCOME BACK',
          'Login your account.': 'Login your account.',
          "Login With Mobile Number": "Login With Mobile Number",
          "Login With Email Address": "Login With Email Address",
          'Enter Mobile Number': 'Enter Mobile Number',
          'Please enter phone number': 'Please enter phone number',
          'Phone Number not register yet Please Signup':
              'Phone Number not register yet Please Signup',
          "OTP has been sent": "OTP has been sent",
          "Oops, OTP send failed": "Oops, OTP send failed",
          'Email not register yet Please Signup':
              'Email not register yet Please Signup',
          'Enter your Mobile number': 'Enter your Mobile number',
          'Please enter your phone number': 'Please enter your phone number',
          'Please enter your email': 'Please enter your email',
          'Enter a valid email address': 'Enter a valid email address',
          'Please enter your otp': 'Please enter your otp',
          'Enter Email': 'Enter Email',
          'send': 'send',
          'Enter Otp': 'Enter Otp',
          "OTP is verified": "OTP is verified",
          "Invalid OTP": "Invalid OTP",
          'Login': 'Login',
          'Customer Booking?': 'Customer Booking?',
          'Sign in as a business': 'Sign in as a business',
          'Or Login with': 'Or Login with',
          'Facebook': 'Facebook',
          'Google': 'Google',
          "Don't Have an Account?": "Don't Have an Account?",
          'Signup': 'Signup',
          'Email already exits': 'Email already exits',
          'Mobile Number already exits': 'Mobile Number already exits',
          "Create Account": "Create Account",
          "Enter Your Name": "Enter Your Name",
          "Please enter your name": "Please enter your name",
          'Enter your Email': 'Enter your Email',
          "Valid Email is required": "Valid Email is required",
          "Email is required": "Email is required",
          "Please accept term and conditions":
              "Please accept term and conditions",
          "Email": "Email",
          "Mobile Number": "Mobile Number",
          'Phone Number': 'Phone Number',
          'Are you agree terms and conditions?':
              'Are you agree terms and conditions?',
          "Already Have an Account?": "Already Have an Account?",
          "Address": "Address",
          "Location": "Location",
          'Yes I understand and agree to the':
              'Yes I understand and agree to the',
          'Terms And Conditions': 'Terms And Conditions',
          'Save': 'Save',
          'Sent OTP  to verify your number': 'Sent OTP  to verify your number',
          'Enter the OTP Send to': 'Enter the OTP Send to',
          'RESEND OTP': 'RESEND OTP',
          'THANK YOU': 'THANK YOU',
          'your account has been successfully created':
              'your account has been successfully created',
          "CONTINUE": "CONTINUE",
          'My Orders': 'My Orders',
          "My Profile": "My Profile",
          "Notification": "Notification",
          "My Address": "My Address",
          "Privacy Policy": "Privacy Policy",
          'Help Center': 'Help Center',
          'Log Out': 'Log Out',
          "Profile": "Profile",
          'Home': 'Home',
          "Find for food or restaurant...": "Find for food or restaurant...",
          'Near By': 'Near By',
          'Rating': 'Rating',
          "Offers": "Offers",
          "Offer": "Offer",
          "Popular": "Popular",
          'Restaurants chosen for you': 'Restaurants chosen for you',
          'Explore Now': 'Explore Now',
          'Popular restaurants in Madrid': 'Popular restaurants in Madrid',
          "Status": "Status",
          "Complete Address": "Complete Address",
          "Choose Address": "Choose Address",
          "Enter complete address": "Enter complete address",
          "Office": "Office",
          "Hotel": "Hotel",
          "Other": "Other",
          "Flat, House no, Floor, Tower,Street":
              "Flat, House no, Floor, Tower,Street",
          "Street, Society, Landmark": "Street, Society, Landmark",
          'Select city': 'Select city',
          "Recipient’s name": "Recipient’s name",
          'save address': 'save address',
          'Address Added': 'Address Added',
          "No Address Found": "No Address Found",
          "Edit": "Edit",
          "Delete": "Delete",
          "Are you sure you want to delete this Address":
              "Are you sure you want to delete this Address",
          "CheckOut": "CheckOut",
          'Deliver To': 'Deliver To',
          "Please choose address": "Please choose address",
          'Use Coupons': 'Use Coupons',
          'Applied Successfully': 'Applied Successfully',
          'You saved': 'You saved',
          'Subtotal': 'Subtotal',
          'Tax And Fees': 'Tax And Fees',
          'Delivery': 'Delivery',
          'Save Coupon': 'Save Coupon',
          'Save Coupon Code': 'Save Coupon Code',
          'Total': 'Total',
          'Items': 'Items',
          "Payment Method": "Payment Method",
          'Debit/Credit Card': 'Debit/Credit Card',
          'PayPal': 'PayPal',
          "Place Order": "Place Order",
          "Cart is empty": "Cart is empty",
          "Browse": "Browse",
          "Check Order Details": "Check Order Details",
          "your reservation is confirmed": "your reservation is confirmed",
          "Your OrderId:": "Your OrderId:",
          "Delivery Orders": "Delivery Orders",
          "Active": "Active",
          "Completed": "Completed",
          "Cancelled": "Cancelled",
          "Cancel Order": "Cancel Order",
          "See Details": "See Details",
          'Empty': 'Empty',
          'You do not have an active order of this time':
              'You do not have an active order of this time',
          "Leave Review": "Leave Review",
          "Order Again": "Order Again",
          "Time": "Time",
          "Guest": "Guest",
          "Cancel": "Cancel",
          "okay": "okay",
          "Upload images": "Upload images",
          'Dining': 'Dining',
          'Please select image': 'Please select image',
          'Please select booking type': 'Please select booking type',
          'Select Picture from': 'Select Picture from',
          'Cropper': 'Cropper',
          "Camera": "Camera",
          'Gallery': 'Gallery',
          'Orders': 'Orders',
          'Wallet': 'Wallet',
          'Order List': 'Order List',
          "Filter": "Filter",
          "Yes": "Yes",
          "No": "No",
          "False": "False",
          "True": "True",
          "Search": "Search",
          "Dining Orders": "Dining Orders",
          "No User Found": "No User Found",
          "Date": "Date",
          "Name": "Name",
          'Please enter about yourself': 'Please enter about yourself',
          "Upload Restaurant Images or Videos":
              "Upload Restaurant Images or Videos",
          "Upload Restaurant Menu Card": "Upload Restaurant Menu Card",
          'Image Gallery': 'Image Gallery',
          'Choose From Gallery': 'Choose From Gallery',
          "No Coupon Found": "No Coupon Found",
          "Create promo code": "Create promo code",
          "Update promo code": "Update promo code",
          'Code is Updated': 'Code is Updated',
          'Code is Created': 'Code is Created',
          "Promo Code Name": "Promo Code Name",
          'Please enter your Promo Code Name ':
              'Please enter your Promo Code Name ',
          'Sunday Code': 'Sunday Code',
          'Code': 'Code',
          'Happy sunday': 'Happy sunday',
          'Please enter your Code ': 'Please enter your Code ',
          'Please enter your Discount ': 'Please enter your Discount ',
          "Max Discount": "Max Discount",
          "Start Date": "Start Date",
          'Please enter start Date ': 'Please enter start Date ',
          'Select Start Date': 'Select Start Date',
          "End Date": "End Date",
          'Please enter end Date ': 'Please enter end Date ',
          'Select End Date': 'Select End Date',
          'UPDATE COUPON': 'UPDATE COUPON',
          'CREATE COUPON': 'CREATE COUPON',
          'basad on 23 reviews': 'basad on 23 reviews',
          'Excellent        ': 'Excellent        ',
          'Good               ': 'Good               ',
          'Average          ': 'Average          ',
          'Below Average': 'Below Average',
          "Chat/Email": "Chat/Email",
          "Resvago team": "Resvago team",
          "FAQ": "FAQ",
          'here': 'here',
          "Set Delivery": "Set Delivery",
          "Cancellation": "Cancellation",
          "Menu selection": "Menu selection",
          "Preparation time": "Preparation time",
          'Please enter your preparation Time':
              'Please enter your preparation Time',
          '20 Mint': '20 Mint',
          "Average meal for 1 Member": "Average meal for 1 Member",
          'Please enter your average Meal For 1 Member':
              'Please enter your average Meal For 1 Member',
          'Submit': 'Submit',
          "Please enter bank account Name": "Please enter bank account Name",
          "Bank Account Number": "Bank Account Number",
          "Please enter bank account number":
              "Please enter bank account number",
          "Account Holder Name": "Account Holder Name",
          "Please enter account holder name":
              "Please enter account holder name",
          "IFSC Code": "IFSC Code",
          "Please enter IFSC code": "Please enter IFSC code",
          "ADD ACCOUNT": "ADD ACCOUNT",
          "Order ID:": "Order ID:",
          "Orders Details": "Orders Details",
          "Selected Items": "Selected Items",
          "Qty:": "Qty:",
          "Restaurant Details": "Restaurant Details",
          "Restaurant Name": "Restaurant Name",
          "Restaurant Number": "Restaurant Number",
          "Restaurant Address": "Restaurant Address",
          "Review": "Review",
          'food quality': 'food quality',
          'food quantity': 'food quantity',
          'How did we do?': 'How did we do?',
          'communication': 'communication',
          'hygiene': 'hygiene',
          "About required": "About required",
          'FeedBack': 'FeedBack',
          'Skip': 'Skip',
          'Restaurants': 'Restaurants',
          'Layers of delicious restoring': 'Layers of delicious restoring',
          'Up to \$10 Master card Cashback': 'Up to \$10 Master card Cashback',
          'Use code Card Above \$120': 'Use code Card Above \$120',
          'Select Date': 'Select Date',
          'Menu List': 'Menu List',
          'Slots not available': 'Slots not available',
          'Please select slot number': 'Please select slot number',
          'Please select guest number': 'Please select guest number',
          'Lunch': 'Lunch',
          'Dinner': 'Dinner',
          'Next': 'Next',
          'Number Of Guests': 'Number Of Guests',
          'We have max': 'We have max',
          'sitting capacity': 'sitting capacity',
          'Select Your Offer': 'Select Your Offer',
          'Off On “A La Carte” Menu': 'Off On “A La Carte” Menu',
          'Discount available for the booked timeslot preset menus and drinks not included':
              'Discount available for the booked timeslot preset menus and drinks not included',
          'off': 'off',
          'No Offer Selected': 'No Offer Selected',
          'Restaurants Menu Chosen For You': 'Restaurants Menu Chosen For You',
          'Please select menu': 'Please select menu',
          'Dine In': 'Dine In',
        },

        //Spanish LANGUAGE
        'es_ES': {
          'Logout' : 'Cerrar sesión',
          'Change Language':'Cambiar idioma',
          'My Wishlist' : 'mi lista de deseos',
          'You first': 'tú primero',
          'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals':
              'No le cobramos tarifas de pedido. No te espiamos. Solo te ayudamos a disfrutar de tus comidas.',
          'Beautifully-designed menus': 'Menús bellamente diseñados',
          'Every menu item is manually reviewed by our team':
              'Nuestro equipo revisa manualmente cada elemento del menú.',
          "Unbeatable rates": "Tarifas inmejorables",
          'We don’t charge any order fees. Delivery fees go where they belong.':
              'No cobramos ninguna tarifa de pedido. Los gastos de envío van a donde pertenecen.',
          'WELCOME BACK': 'BIENVENIDO DE NUEVO',
          'Login your account.': 'Inicie sesión en su cuenta.',
          "Login With Mobile Number": "Iniciar sesión con número de móvil",
          "Login With Email Address":
              "Iniciar sesión con dirección de correo electrónico",
          'Enter Mobile Number': 'Ingrese el número de móvil',
          'Please enter phone number':
              'Por favor ingrese el número de teléfono',
          'Phone Number not register yet Please Signup':
              'Número de teléfono aún no registrado Por favor regístrese',
          "OTP has been sent": "OTP ha sido enviado",
          "Oops, OTP send failed": "Vaya, falló el envío de OTP",
          'Email not register yet Please Signup':
              'Correo electrónico aún no registrado Por favor regístrese',
          'Enter your Mobile number': 'Ingrese su numero celular',
          'Please enter your phone number':
              'Por favor, introduzca su número de teléfono',
          'Please enter your email':
              'Por favor introduzca su correo electrónico',
          'Enter a valid email address':
              'Introduzca una dirección de correo electrónico válida',
          'Please enter your otp': 'Por favor ingresa tu OTP',
          'Enter Email': 'Ingrese correo electrónico',
          'send': 'enviar',
          'Enter Otp': 'Ingrese a OTP',
          "OTP is verified": "OTP está verificado",
          "Invalid OTP": "OTP no válida",
          'Login': 'Acceso',
          'Customer Booking?': '¿Reserva del cliente?',
          'Sign in as a business': 'Iniciar sesión como empresa',
          'Or Login with': 'O inicia sesión con',
          'Facebook': 'Facebook',
          'Google': 'Google',
          "Don't Have an Account?": "¿No tienes una cuenta?",
          'Signup': 'Inscribirse',
          'Email already exits': 'El correo electrónico ya existe',
          'Mobile Number already exits': 'El número de móvil ya existe',
          "Create Account": "Crear una cuenta",
          "Enter Your Name": "Introduzca su nombre",
          "Please enter your name": "por favor, escriba su nombre",
          'Enter your Email': 'Introduce tu correo electrónico',
          "Valid Email is required": "Se requiere un correo electrónico válido",
          "Email is required": "correo electronico es requerido",
          "Please accept term and conditions":
              "Por favor acepte términos y condiciones",
          "Email": "Correo electrónico",
          "Mobile Number": "Número de teléfono móvil",
          'Phone Number': 'Número de teléfono',
          'Are you agree terms and conditions?':
              '¿Estás de acuerdo con los términos y condiciones?',
          "Already Have an Account?": "¿Ya tienes una cuenta?",
          "Address": "DIRECCIÓN",
          "Location": "Ubicación",
          'Yes I understand and agree to the': 'Sí, entiendo y acepto las',
          'Terms And Conditions': 'Términos y condiciones',
          'Save': 'Ahorrar',
          'Sent OTP  to verify your number':
              'Envió OTP para verificar su número',
          'Enter the OTP Send to': 'Ingrese el OTP Enviar a',
          'RESEND OTP': 'REENVIAR OTP',
          'THANK YOU': 'GRACIAS',
          'your account has been successfully created':
              'Su cuenta ha sido creada satisfactoriamente',
          "CONTINUE": "CONTINUAR",
          'My Orders': 'Mis ordenes',
          "My Profile": "Mi perfil",
          "Notification": "Notificación",
          "My Address": "Mi dirección",
          "Privacy Policy": "política de privacidad",
          'Help Center': 'Centro de ayuda',
          'Log Out': 'Cerrar sesión',
          "Profile": "Perfil",
          'Home': 'Hogar',
          "Find for food or restaurant...":
              "Buscar para comida o restaurante...",
          'Near By': 'Cercano',
          'Rating': 'Clasificación',
          "Offers": "Ofertas",
          "Offer": "Oferta",
          "Popular": "Popular",
          'Restaurants chosen for you': 'Restaurantes elegidos para ti',
          'Explore Now': 'Explora ahora',
          'Popular restaurants in Madrid': 'Restaurantes populares en Madrid',
          "Status": "Estado",
          "Complete Address": "Completa tu direccion",
          "Choose Address": "Completa tu direccion",
          "Enter complete address": "Introduzca la dirección completa",
          "Office": "Oficina",
          "Hotel": "Hotel",
          "Other": "Otro",
          "Flat, House no, Floor, Tower,Street":
              "Piso, Casa no, Piso, Torre, Calle",
          "Street, Society, Landmark": "Calle, Sociedad, Hito",
          'Select city': 'Ciudad selecta',
          "Recipient’s name": "Nombre del destinatario",
          'save address': 'guardar dirección',
          'Address Added': 'Dirección agregada',
          "No Address Found": "No se encontró ninguna dirección",
          "Edit": "Editar",
          "Delete": "Borrar",
          "Are you sure you want to delete this Address":
              "¿Estás seguro de que deseas eliminar esta dirección?",
          "CheckOut": "Verificar",
          'Deliver To': 'Entregar a',
          "Please choose address": "Por favor elige la dirección",
          'Use Coupons': 'Usar cupones',
          'Applied Successfully': 'Aplicado con éxito',
          'You saved': 'Salvaste',
          'Subtotal': 'Total parcial',
          'Tax And Fees': 'Impuestos y tasas',
          'Delivery': 'Entrega',
          'Save Coupon' : 'Guardar cupón',
          'Save Coupon Code': 'Guardar código de cupón',
          'Total': 'Total',
          'Items': 'Elementos',
          "Payment Method": "Método de pago",
          'Debit/Credit Card': 'Tarjeta de crédito débito',
          'PayPal': 'PayPal',
          "Place Order": "Realizar pedido",
          "Cart is empty": "El carrito esta vacío",
          "Browse": "Navegar",
          "Check Order Details": "Ver detalles del pedido",
          "your reservation is confirmed": "Su reservacion esta confirmada",
          "Your OrderId:": "Su ID de pedido:",
          "Delivery Orders": "Órdenes de entrega",
          "Active": "Activo",
          "Completed": "Terminado",
          "Cancelled": "Cancelado",
          "Cancel Order": "Cancelar orden",
          "See Details": "Ver detalles",
          'Empty': 'Vacío',
          'You do not have an active order of this time':
              'No tienes un pedido activo de este momento',
          "Leave Review": "Deje opinión",
          "Order Again": "Ordene nuevamente",
          "Time": "Tiempo",
          "Guest": "Invitado",
          "Cancel": "Cancelar",
          "okay": "bueno",
          "Upload images": "Subir imágenes",
          'Dining': 'Comida',
          'Please select image': 'Por favor seleccione imagen',
          'Please select booking type':
              'Por favor seleccione el tipo de reserva',
          'Select Picture from': 'Seleccione Imagen de',
          'Cropper': 'Cultivador',
          "Camera": "Cámara",
          'Gallery': 'Galería',
          'Orders': 'Pedidos',
          'Wallet': 'Billetera',
          'Order List': 'Lista de orden',
          "Filter": "Filtrar",
          "Yes": "Sí",
          "No": "No",
          "False": "Falso",
          "True": "Verdadero",
          "Search": "Buscar",
          "Dining Orders": "Órdenes de cena",
          "No User Found": "Usuario no encontrado",
          "Date": "Fecha",
          "Name": "Nombre",
          'Please enter about yourself': 'Por favor ingresa sobre ti',
          "Upload Restaurant Images or Videos":
              "Subir imágenes o vídeos de restaurantes",
          "Upload Restaurant Menu Card":
              "Cargar tarjeta de menú de restaurante",
          'Image Gallery': 'galería de imágenes',
          'Choose From Gallery': 'Elegir de la galería',
          "No Coupon Found": "No se encontró ningún cupón",
          "Create promo code": "Crear código promocional",
          "Update promo code": "Actualizar código promocional",
          'Code is Updated': 'El código está actualizado',
          'Code is Created': 'Se crea el código',
          "Promo Code Name": "Nombre del código promocional",
          'Please enter your Promo Code Name ':
              'Por favor ingrese el nombre de su código promocional',
          'Sunday Code': 'Código dominical',
          'Code': 'Código',
          'Happy sunday': 'Feliz domingo',
          'Please enter your Code ': 'Por favor ingresa tu código',
          'Please enter your Discount ': 'Por favor ingrese su descuento',
          "Max Discount": "Descuento máximo",
          "Start Date": "Fecha de inicio",
          'Please enter start Date ': 'Por favor ingrese la fecha de inicio',
          'Select Start Date': 'Seleccione la fecha de inicio',
          "End Date": "Fecha final",
          'Please enter end Date ':
              'Por favor ingrese la fecha de finalización',
          'Select End Date': 'Seleccionar fecha de finalización',
          'UPDATE COUPON': 'ACTUALIZAR CUPÓN',
          'CREATE COUPON': 'CREAR CUPÓN',
          'basad on 23 reviews': 'Basado en 23 opiniones',
          'Excellent        ': 'Excelente',
          'Good               ': 'Bueno',
          'Average          ': 'Promedio',
          'Below Average': 'Por debajo del promedio',
          "Chat/Email": "Chat/correo electrónico",
          "Resvago team": "equipo resvago",
          "FAQ": "Preguntas más frecuentes",
          'here': 'aquí',
          "Set Delivery": "Establecer entrega",
          "Cancellation": "Cancelación",
          "Menu selection": "Selección de menú",
          "Preparation time": "Tiempo de preparación",
          'Please enter your preparation Time':
              'Por favor ingrese su tiempo de preparación',
          'Mint': 'menta',
          "Average meal for 1 Member": "Comida promedio para 1 Miembro",
          'Please enter your average Meal For 1 Member':
              'Por favor ingrese su comida promedio para 1 miembro',
          'Submit': 'Entregar',
          "Please enter bank account Name":
              "Por favor ingrese el nombre de la cuenta bancaria",
          "Bank Account Number": "Número de cuenta bancaria",
          "Please enter bank account number":
              "Por favor ingrese el número de cuenta bancaria",
          "Account Holder Name": "nombre del titular de la cuenta",
          "Please enter account holder name":
              "Por favor ingrese el nombre del titular de la cuenta",
          "IFSC Code": "Código IFSC",
          "Please enter IFSC code": "Por favor ingrese el código IFSC",
          "ADD ACCOUNT": "AÑADIR CUENTA",
          "Order ID:": "Solicitar ID:",
          "Orders Details": "Detalles de pedidos",
          "Selected Items": "Artículos seleccionados",
          "Qty:": "Cantidad:",
          "Restaurant Details": "Detalles del restaurante",
          "Restaurant Name": "Nombre del restaurante",
          "Restaurant Number": "Número de restaurante",
          "Restaurant Address": "Dirección del restaurante",
          "Review": "Revisar",
          'food quality': 'calidad de la comida',
          'food quantity': 'cantidad de comida',
          'How did we do?': 'Como lo hicimos',
          'communication': 'comunicación',
          'hygiene': 'higiene',
          "About required": "Acerca de lo requerido",
          'FeedBack': 'Comentario',
          'Skip': 'Saltar',
          'Restaurants': 'Restaurantes',
          'Layers of delicious restoring': 'Capas de deliciosa restauración',
          'Up to \$10 Master card Cashback':
              'Hasta \$10 de reembolso en tarjeta Master Card',
          'Use code Card Above \$120': 'Usar código Tarjeta superior a \$120',
          'Select Date': 'Seleccione fecha',
          'Menu List': 'Lista de menú',
          'Slots not available': 'Ranuras no disponibles',
          'Please select slot number':
              'Por favor seleccione el número de ranura',
          'Please select guest number':
              'Por favor seleccione el número de huésped',
          'Lunch': 'Almuerzo',
          'Dinner': 'Cena',
          'Next': 'Próximo',
          'Number Of Guests': 'Numero de invitados',
          'We have max': 'Nosotros tenemos max',
          'sitting capacity': 'capacidad para sentarse',
          'Select Your Offer': 'Selecciona tu oferta',
          'Off On “A La Carte” Menu': 'Desactivado Activado Menú “A la carta”',
          'Discount available for the booked timeslot preset menus and drinks not included':
              'Descuento disponible para los menús preestablecidos de la franja horaria reservada y bebidas no incluidas.',
          'off': 'apagado',
          'No Offer Selected': 'Ninguna oferta seleccionada',
          'Restaurants Menu Chosen For You':
              'Menú de restaurantes elegido para ti',
          'Please select menu': 'Por favor seleccione el menú',
          'Dine In': 'Cenar en',
        },

        // french Language
        'fr_FR': {
          'Logout' : 'Se déconnecter',
          'Change Language':'Changer de langue',
          'My Wishlist' : 'Ma liste denvies',
          'You first': 'Toi en premier',
          'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals':
              'Nous ne vous facturons pas de frais de commande. Nous ne vous espionnons pas. Nous vous aidons simplement à profiter de vos repas',
          'Beautifully-designed menus': 'Des menus magnifiquement conçus',
          'Every menu item is manually reviewed by our team':
              'Chaque élément du menu est examiné manuellement par notre équipe',
          "Unbeatable rates": "Des tarifs imbattables",
          'We don’t charge any order fees. Delivery fees go where they belong.':
              'Nous ne facturons aucun frais de commande. Les frais de livraison vont là où ils appartiennent.',
          'WELCOME BACK': 'CONTENT DE TE REVOIR',
          'Login your account.': 'Connectez-vous à votre compte.',
          "Login With Mobile Number": "Connectez-vous avec un numéro de mobile",
          "Login With Email Address": "Connectez-vous avec une adresse e-mail",
          'Enter Mobile Number': 'Entrez le numéro de portable',
          'Please enter phone number': 'Veuillez entrer le numéro de téléphone',
          'Phone Number not register yet Please Signup':
              'Le numéro de téléphone n\'est pas encore enregistré Veuillez vous inscrire',
          "OTP has been sent": "OTP a été envoyé",
          "Oops, OTP send failed": "Oups, l'envoi OTP a échoué",
          'Email not register yet Please Signup':
              'E-mail pas encore enregistré Veuillez vous inscrire',
          'Enter your Mobile number': 'Entrez votre numéro de mobile',
          'Please enter your phone number':
              'Veuillez entrer votre numéro de téléphone',
          'Please enter your email': 'Veuillez entrer votre email',
          'Enter a valid email address': 'Entrez une adresse mail valide',
          'Please enter your otp': 'Veuillez entrer votre OTP',
          'Enter Email': 'Entrez votre e-mail',
          'send': 'envoyer',
          'Enter Otp': 'Entrez OTP',
          "OTP is verified": "OTP est vérifié",
          "Invalid OTP": "OTP invalide",
          'Login': 'Se connecter',
          'Customer Booking?': 'Réservation client ?',
          'Sign in as a business': 'Connectez-vous en tant qu\'entreprise',
          'Or Login with': 'Ou connectez-vous avec',
          'Facebook': 'Facebook',
          'Google': '',
          "Don't Have an Account?": "Vous n'avez pas de compte ?",
          'Signup': 'S\'inscrire',
          'Email already exits': 'L\'e-mail existe déjà',
          'Mobile Number already exits': 'Le numéro de mobile existe déjà',
          "Create Account": "Créer un compte",
          "Enter Your Name": "Entrez votre nom",
          "Please enter your name": "S'il vous plaît entrez votre nom",
          'Enter your Email': 'Entrer votre Email',
          "Valid Email is required": "Un e-mail valide est requis",
          "Email is required": "L'e-mail est requis",
          "Please accept term and conditions":
              "Veuillez accepter les termes et conditions",
          "Email": "E-mail",
          "Mobile Number": "Numéro de portable",
          'Phone Number': 'Numéro de téléphone',
          'Are you agree terms and conditions?':
              'Êtes-vous d’accord avec les termes et conditions ?',
          "Already Have an Account?": "Vous avez déjà un compte?",
          "Address": "Adresse",
          "Location": "Emplacement",
          'Yes I understand and agree to the':
              'Oui, je comprends et j\'accepte le',
          'Terms And Conditions': 'Termes et conditions',
          'Save': 'Sauvegarder',
          'Sent OTP  to verify your number':
              'Envoyé OTP pour vérifier votre numéro',
          'Enter the OTP Send to': 'Entrez l\'OTP Envoyer à',
          'RESEND OTP': 'RENVOYER OTP',
          'THANK YOU': 'MERCI',
          'your account has been successfully created':
              'Votre compte à été créé avec succès',
          "CONTINUE": "CONTINUER",
          'My Orders': 'Mes commandes',
          "My Profile": "Mon profil",
          "Notification": "Mon profil",
          "My Address": "Mon adresse",
          "Privacy Policy": "politique de confidentialité",
          'Help Center': 'Centre d\'aide',
          'Log Out': 'Se déconnecter',
          "Profile": "Profil",
          'Home': 'Maison',
          "Find for food or restaurant...":
              "Trouver pour la nourriture ou le restaurant...",
          'Near By': 'Proche',
          'Rating': 'Notation',
          "Offers": "Des offres",
          "Offer": "Offre",
          "Popular": "Populaire",
          'Restaurants chosen for you': 'Des restaurants choisis pour vous',
          'Explore Now': 'Explorez maintenant',
          'Popular restaurants in Madrid': 'Restaurants populaires à Madrid',
          "Status": "Statut",
          "Complete Address": "Adresse complète",
          "Choose Address": "Choisissez l'adresse",
          "Enter complete address": "Entrez l'adresse complète",
          "Office": "Bureau",
          "Hotel": "Hôtel",
          "Other": "Autre",
          "Flat, House no, Floor, Tower,Street":
              "Appartement, Numéro de maison, Étage, Tour, Rue",
          "Street, Society, Landmark": "Rue, Société, Point De Repère",
          'Select city': 'Sélectionnez une ville',
          "Recipient’s name": "Nom du destinataire",
          'save address': 'enregistrer l\'adresse',
          'Address Added': 'Adresse ajoutée',
          "No Address Found": "Aucune adresse trouvée",
          "Edit": "Modifier",
          "Delete": "Supprimer",
          "Are you sure you want to delete this Address":
              "Êtes-vous sûr de vouloir supprimer cette adresse",
          "CheckOut": "Vérifier",
          'Deliver To': 'Livrer à',
          "Please choose address": "Veuillez choisir l'adresse",
          'Use Coupons': 'Utiliser des coupons',
          'Applied Successfully': 'Appliqué avec succès',
          'You saved': 'Tu as sauvegardé',
          'Subtotal': 'Total',
          'Tax And Fees': 'Taxes et frais',
          'Delivery': 'Livraison',
          'Save Coupon Code': 'Enregistrer le code promo',
          'Save Coupon' : 'Enregistrer le coupon',
          'Total': 'Totale',
          'Items': 'Articles',
          "Payment Method": "Mode de paiement",
          'Debit/Credit Card': 'Carte de débit/crédit',
          'PayPal': 'Pay Pal',
          "Place Order": "Passer la commande",
          "Cart is empty": "Le panier est vide",
          "Browse": "Parcourir",
          "Check Order Details": "Vérifier les détails de la commande",
          "your reservation is confirmed": "Votre réservation est confirmée",
          "Your OrderId:": "Votre numéro de commande :",
          "Delivery Orders": "Bons de livraison",
          "Active": "Actif",
          "Completed": "Complété",
          "Cancelled": "Annulé",
          "Cancel Order": "annuler la commande",
          "See Details": "Voir les détails",
          'Empty': 'Vide',
          'You do not have an active order of this time':
              'Vous n\'avez pas de commande active pour cette période',
          "Leave Review": "Laisser un avis",
          "Order Again": "Commandez à nouveau",
          "Time": "Temps",
          "Guest": "Invitée",
          "Cancel": "Annuler",
          "okay": "d'accord",
          "Upload images": "Importer des images",
          'Dining': 'À manger',
          'Please select image': 'Veuillez sélectionner une image',
          'Please select booking type':
              'Veuillez sélectionner le type de réservation',
          'Select Picture from': 'Sélectionnez une image dans',
          'Cropper': 'Recadrage',
          "Camera": "Caméra",
          'Gallery': 'Galerie',
          'Orders': 'Ordres',
          'Wallet': 'Portefeuille',
          'Order List': 'Liste de commande',
          "Filter": "Filtre",
          "Yes": "Oui",
          "No": "Non",
          "False": "FAUX",
          "True": "Vrai",
          "Search": "Recherche",
          "Dining Orders": "Commandes de restauration",
          "No User Found": "Aucun utilisateur trouvé",
          "Date": "Date",
          "Name": "Nom",
          'Please enter about yourself': 'Veuillez entrer à propos de vous',
          "Upload Restaurant Images or Videos":
              "Télécharger des images ou des vidéos de restaurants",
          "Upload Restaurant Menu Card":
              "Télécharger la carte du menu du restaurant",
          'Image Gallery': 'Galerie d\'images',
          'Choose From Gallery': 'Choisir depuis la galerie',
          "No Coupon Found": "Aucun coupon trouvé",
          "Create promo code": "Créer un code promotionnel",
          "Update promo code": "Mettre à jour le code promotionnel",
          'Code is Updated': 'Le code est mis à jour',
          'Code is Created': 'Le code est créé',
          "Promo Code Name": "Nom du code promotionnel",
          'Please enter your Promo Code Name ':
              'Veuillez saisir le nom de votre code promotionnel ',
          'Sunday Code': 'Code du dimanche',
          'Code': 'Code',
          'Happy sunday': 'Bon dimanche',
          'Please enter your Code ': 'Veuillez entrer votre code ',
          'Please enter your Discount ': 'Veuillez entrer votre réduction ',
          "Max Discount": "Remise maximale",
          "Start Date": "Date de début",
          'Please enter start Date ': 'Veuillez entrer la date de début ',
          'Select Start Date': 'Sélectionnez la date de début',
          "End Date": "Date de fin",
          'Please enter end Date ': 'Veuillez entrer la date de fin ',
          'Select End Date': 'Sélectionnez la date de fin',
          'UPDATE COUPON': 'COUPON DE MISE À JOUR',
          'CREATE COUPON': 'CRÉER UN COUPON',
          'basad on 23 reviews': 'basad sur 23 avis',
          'Excellent        ': 'Excellent',
          'Good               ': 'Bien',
          'Average          ': 'Moyenne',
          'Below Average': 'Sous la moyenne',
          "Chat/Email": "Chat/E-mail",
          "Resvago team": "L'équipe Resvago",
          "FAQ": "FAQ",
          'here': 'ici',
          "Set Delivery": "Définir la livraison",
          "Cancellation": "Annulation",
          "Menu selection": "Sélection des menus",
          "Preparation time": "Temps de préparation",
          'Please enter your preparation Time':
              'Veuillez entrer votre temps de préparation',
          'Mint': 'Minute',
          "Average meal for 1 Member": "Repas moyen pour 1 Membre",
          'Please enter your average Meal For 1 Member':
              'Veuillez entrer votre repas moyen pour 1 membre',
          'Submit': 'Soumettre',
          "Please enter bank account Name":
              "Veuillez saisir le nom du compte bancaire",
          "Bank Account Number": "Numéro de compte bancaire",
          "Please enter bank account number":
              "Veuillez saisir le numéro de compte bancaire",
          "Account Holder Name": "Nom du titulaire du compte",
          "Please enter account holder name":
              "Veuillez saisir le nom du titulaire du compte",
          "IFSC Code": "Code IFSC",
          "Please enter IFSC code": "Veuillez entrer le code IFSC",
          "ADD ACCOUNT": "AJOUTER UN COMPTE",
          "Order ID:": "Numéro de commande:",
          "Orders Details": "Détails des commandes",
          "Selected Items": "Articles sélectionnés",
          "Qty:": "Quantité :",
          "Restaurant Details": "Détails du restaurant",
          "Restaurant Name": "Nom du restaurant",
          "Restaurant Number": "Numéro du restaurant",
          "Restaurant Address": "Adresse du restaurant",
          "Review": "Revoir",
          'food quality': 'qualité de la nourriture',
          'food quantity': 'quantité de nourriture',
          'How did we do?': 'Comment avons-nous fait ?',
          'communication': 'communication',
          'hygiene': 'hygiène',
          "About required": "À propos requis",
          'FeedBack': 'Retour',
          'Skip': 'Sauter',
          'Restaurants': 'Restaurants',
          'Layers of delicious restoring':
              'Des couches de restauration délicieuse',
          'Up to \$10 Master card Cashback':
              'Jusqu\'à 10 \$ de remise en argent sur la carte Master',
          'Use code Card Above \$120':
              'Utilisez le code de la carte ci-dessus 120 \$',
          'Select Date': 'Sélectionner une date',
          'Menu List': 'Liste des menus',
          'Slots not available': 'Emplacements non disponibles',
          'Please select slot number':
              'Veuillez sélectionner le numéro d\'emplacement',
          'Please select guest number':
              'Veuillez sélectionner le numéro d\'invité',
          'Lunch': 'Déjeuner',
          'Dinner': 'Dîner',
          'Next': 'Suivante',
          'Number Of Guests': 'Nombre d\'invités',
          'We have max': 'Nous avons maximum',
          'sitting capacity': 'capacité assise',
          'Select Your Offer': 'Sélectionnez votre offre',
          'Off On “A La Carte” Menu': 'Désactivé Sur Menu « À la carte »',
          'Discount available for the booked timeslot preset menus and drinks not included':
              'Remise disponible sur les menus prédéfinis du créneau horaire réservé et boissons non incluses',
          'off': 'désactivé',
          'No Offer Selected': 'Aucune offre sélectionnée',
          'Restaurants Menu Chosen For You':
              'Menu de restaurants choisi pour vous',
          'Please select menu': 'Veuillez sélectionner le menu',
          'Dine In': 'Dîner dans',
        },

        // Arabic Language
        'ar_AE': {
          'Logout' : 'تسجيل خروج',
          'Change Language' : 'تغيير اللغة',
          'My Wishlist': 'قائمة امنياتي',
          'You first': 'أنت أولاً',
          'We don’t charge you order fees. We don’t spy on you. We just help you enjoy your meals':
              'نحن لا نفرض عليك رسوم الطلب. نحن لا نتجسس عليك. نحن نساعدك فقط على الاستمتاع بوجباتك',
          'Beautifully-designed menus': 'قوائم مصممة بشكل جميل',
          'Every menu item is manually reviewed by our team':
              'تتم مراجعة كل عنصر في القائمة يدويًا بواسطة فريقنا',
          "Unbeatable rates": "معدلات لا تقبل المنافسة",
          'We don’t charge any order fees. Delivery fees go where they belong.':
              'نحن لا نفرض أي رسوم على الطلب. رسوم التوصيل تذهب إلى حيث تنتمي.',
          'WELCOME BACK': 'مرحبًا بعودتك',
          'Login your account.': 'قم بتسجيل الدخول إلى حسابك.',
          "Login With Mobile Number": "تسجيل الدخول برقم الجوال",
          "Login With Email Address":
              "تسجيل الدخول باستخدام عنوان البريد الإلكتروني",
          'Enter Mobile Number': 'أدخل رقم الجوال',
          'Please enter phone number': 'الرجاء إدخال رقم الهاتف',
          'Phone Number not register yet Please Signup':
              'رقم الهاتف لم يتم التسجيل بعد الرجاء الاشتراك',
          "OTP has been sent": "تم إرسال كلمة المرور لمرة واحدة",
          "Oops, OTP send failed": "عفوًا، فشل إرسال OTP",
          'Email not register yet Please Signup':
              'البريد الإلكتروني لم يتم التسجيل بعد يرجى الاشتراك',
          'Enter your Mobile number': 'أدخل رقم هاتفك المحمول',
          'Please enter your phone number': 'يرجى إدخال رقم الهاتف الخاص بك',
          'Please enter your email': 'رجاءا أدخل بريدك الإلكتروني',
          'Enter a valid email address': 'أدخل عنوان بريد إلكتروني صالح',
          'Please enter your otp': 'الرجاء إدخال كلمة المرور الخاصة بك',
          'Enter Email': 'أدخل البريد الإلكتروني',
          'send': 'يرسل',
          'Enter Otp': 'أدخل كلمة المرور',
          "OTP is verified": "تم التحقق من OTP",
          "Invalid OTP": "كلمة المرور لمرة واحدة غير صالحة",
          'Login': 'تسجيل الدخول',
          'Customer Booking?': 'حجز العملاء؟',
          'Sign in as a business': 'تسجيل الدخول كعمل تجاري',
          'Or Login with': 'أو تسجيل الدخول باستخدام',
          'Facebook': 'فيسبوك',
          'Google': 'جوجل',
          "Don't Have an Account?": "ليس لديك حساب؟",
          'Signup': 'اشتراك',
          'Email already exits': 'البريد الإلكتروني يخرج بالفعل',
          'Mobile Number already exits': 'رقم الجوال موجود بالفعل',
          "Create Account": "إنشاء حساب",
          "Enter Your Name": "أدخل أسمك",
          "Please enter your name": "من فضلك أدخل إسمك",
          'Enter your Email': 'أدخل بريدك الإلكتروني',
          "Valid Email is required": "مطلوب بريد إلكتروني صالح",
          "Email is required": "البريد الالكتروني مطلوب",
          "Please accept term and conditions": "يرجى قبول الشروط والأحكام",
          "Email": "بريد إلكتروني",
          "Mobile Number": "رقم الهاتف المحمول",
          'Phone Number': 'رقم التليفون',
          'Are you agree terms and conditions?':
              'هل أنت موافق على الشروط والأحكام؟',
          "Already Have an Account?": "هل لديك حساب؟",
          "Address": "عنوان",
          "Location": "موقع",
          'Yes I understand and agree to the': 'نعم أفهم وأوافق على',
          'Terms And Conditions': 'الأحكام والشروط',
          'Save': 'يحفظ',
          'Sent OTP  to verify your number': 'تم إرسال OTP للتحقق من رقمك',
          'Enter the OTP Send to': 'أدخل كلمة مرور OTP أرسل إلى',
          'RESEND OTP': 'إعادة إرسال OTP',
          'THANK YOU': 'شكرًا لك',
          'your account has been successfully created': 'تم إنشاء حسابك بنجاح',
          "CONTINUE": "يكمل",
          'My Orders': 'طلباتي',
          "My Profile": "ملفي",
          "Notification": "إشعار",
          "My Address": "عنواني",
          "Privacy Policy": "سياسة الخصوصية",
          'Help Center': 'مركز المساعدة',
          'Log Out': 'تسجيل خروج',
          "Profile": "مظهر جانبي",
          'Home': 'بيت',
          "Find for food or restaurant...": "ابحث عن طعام أو مطعم...",
          'Near By': 'مجاور',
          'Rating': 'تقييم',
          "Offers": "عروض",
          "Offer": "يعرض",
          "Popular": "شائع",
          'Restaurants chosen for you': 'المطاعم المختارة لك',
          'Explore Now': 'اكتشف الآن',
          'Popular restaurants in Madrid': 'المطاعم الشعبية في مدريد',
          "Status": "حالة",
          "Complete Address": "العنوان الكامل",
          "Choose Address": "اختر العنوان",
          "Enter complete address": "أدخل العنوان الكامل",
          "Office": "مكتب",
          "Hotel": "الفندق",
          "Other": "آخر",
          "Flat, House no, Floor, Tower,Street":
              "شقة، رقم المنزل، الطابق، البرج، الشارع",
          "Street, Society, Landmark": "الشارع، المجتمع، المعلم",
          'Select city': 'اختر مدينة',
          "Recipient’s name": "اسم المستقبل",
          'save address': 'حفظ العنوان',
          'Address Added': 'تمت إضافة العنوان',
          "No Address Found": "لم يتم العثور على عنوان",
          "Edit": "يحرر",
          "Delete": "يمسح",
          "Are you sure you want to delete this Address":
              "هل أنت متأكد أنك تريد حذف هذا العنوان",
          "CheckOut": "الدفع",
          'Deliver To': 'يسلم إلى',
          "Please choose address": "الرجاء اختيار العنوان",
          'Use Coupons': 'استخدام كوبونات',
          'Applied Successfully': 'تم التطبيق بنجاح',
          'You saved': 'لقد أنقذت',
          'Subtotal': 'المجموع الفرعي',
          'Tax And Fees': 'الضرائب والرسوم',
          'Delivery': 'توصيل',
          'Save Coupon Code': 'حفظ رمز القسيمة',
          'Save Coupon' : 'حفظ القسيمة',
          'Total': 'المجموع',
          'Items': 'أغراض',
          "Payment Method": "طريقة الدفع او السداد",
          'Debit/Credit Card': 'بطاقة الخصم/الائتمان',
          'PayPal': 'باي بال',
          "Place Order": "مكان الامر",
          "Cart is empty": "البطاقه خاليه",
          "Browse": "تصفح",
          "Check Order Details": "تحقق من تفاصيل الطلب",
          "your reservation is confirmed": "تم التأكد من حجزك",
          "Your OrderId:": "معرف الطلب الخاص بك:",
          "Delivery Orders": "أوامر التسليم",
          "Active": "نشيط",
          "Completed": "مكتمل",
          "Cancelled": "ألغيت",
          "Cancel Order": "الغاء الطلب",
          "See Details": "انظر التفاصيل",
          'Empty': 'فارغ',
          'You do not have an active order of this time':
              'ليس لديك أمر نشط في هذا الوقت',
          "Leave Review": "اترك مراجعة",
          "Order Again": "أجل مرة أخرى",
          "Time": "وقت",
          "Guest": "ضيف",
          "Cancel": "يلغي",
          "okay": "تمام",
          "Upload images": "تحميل الصور",
          'Dining': 'تناول الطعام',
          'Please select image': 'الرجاء اختيار الصورة',
          'Please select booking type': 'الرجاء تحديد نوع الحجز',
          'Select Picture from': 'حدد صورة من',
          'Cropper': 'كروبر',
          "Camera": "آلة تصوير",
          'Gallery': 'صالة عرض',
          'Orders': 'طلبات',
          'Wallet': 'محفظة',
          'Order List': 'لائحة الطلبات',
          "Filter": "منقي",
          "Yes": "نعم",
          "No": "لا",
          "False": "خطأ شنيع",
          "True": "حقيقي",
          "Search": "يبحث",
          "Dining Orders": "طلبات الطعام",
          "No User Found": "لم يتم العثور على المستخدم",
          "Date": "تاريخ",
          "Name": "اسم",
          'Please enter about yourself': 'الرجاء الدخول عن نفسك',
          "Upload Restaurant Images or Videos":
              "قم بتحميل صور أو مقاطع فيديو للمطعم",
          "Upload Restaurant Menu Card": "تحميل بطاقة قائمة المطعم",
          'Image Gallery': 'معرض الصور',
          'Choose From Gallery': 'اختر من المعرض',
          "No Coupon Found": "لم يتم العثور على قسيمة",
          "Create promo code": "إنشاء رمز ترويجي",
          "Update promo code": "تحديث الرمز الترويجي",
          'Code is Updated': 'تم تحديث الكود',
          'Code is Created': 'تم إنشاء الكود',
          "Promo Code Name": "اسم الرمز الترويجي",
          'Please enter your Promo Code Name ':
              'الرجاء إدخال اسم الرمز الترويجي الخاص بك',
          'Sunday Code': 'كود الأحد',
          'Code': 'شفرة',
          'Happy sunday': 'يوم احد سعيد',
          'Please enter your Code ': 'الرجاء إدخال الرمز الخاص بك',
          'Please enter your Discount ': 'الرجاء إدخال الخصم الخاص بك',
          "Max Discount": "ماكس الخصم",
          "Start Date": "تاريخ البدء",
          'Please enter start Date ': 'الرجاء إدخال تاريخ البدء',
          'Select Start Date': 'حدد تاريخ البدء',
          "End Date": "تاريخ الانتهاء",
          'Please enter end Date ': 'الرجاء إدخال تاريخ الانتهاء',
          'Select End Date': 'حدد تاريخ الانتهاء',
          'UPDATE COUPON': 'تحديث القسيمة',
          'CREATE COUPON': 'إنشاء قسيمة',
          'basad on 23 reviews': 'بناءً على 23 تعليقًا',
          'Excellent        ': 'ممتاز',
          'Good               ': 'جيد',
          'Average          ': 'متوسط',
          'Below Average': 'أقل من المتوسط',
          "Chat/Email": "الدردشة/البريد الإلكتروني",
          "Resvago team": "فريق ريسفاجو",
          "FAQ": "أسئلة مكررة",
          'here': 'هنا',
          "Set Delivery": "تعيين التسليم",
          "Cancellation": "إلغاء",
          "Menu selection": "اختيار القائمة",
          "Preparation time": "وقت التحضير",
          'Please enter your preparation Time':
              'الرجاء إدخال وقت التحضير الخاص بك',
          'Mint': 'دقيقة',
          "Average meal for 1 Member": "متوسط ​​الوجبة لعضو واحد",
          'Please enter your average Meal For 1 Member':
              'الرجاء إدخال متوسط ​​الحصة لعضو واحد',
          'Submit': 'يُقدِّم',
          "Please enter bank account Name": "الرجاء إدخال اسم الحساب البنكي",
          "Bank Account Number": "رقم الحساب المصرفي",
          "Please enter bank account number": "الرجاء إدخال رقم الحساب البنكي",
          "Account Holder Name": "اسم صاحب الحساب",
          "Please enter account holder name": "الرجاء إدخال اسم صاحب الحساب",
          "IFSC Code": "رمز إفسك",
          "Please enter IFSC code": "الرجاء إدخال رمز IFSC",
          "ADD ACCOUNT": "إضافة حساب",
          "Order ID:": "طلب البطاقة التعريفية:",
          "Orders Details": "تفاصيل الطلب",
          "Selected Items": "العناصر المختارة",
          "Qty:": "كمية:",
          "Restaurant Details": "تفاصيل المطعم",
          "Restaurant Name": "اسم المطعم",
          "Restaurant Number": "رقم المطعم",
          "Restaurant Address": "عنوان المطعم",
          "Review": "مراجعة",
          'food quality': 'جودة الطعام',
          'food quantity': 'كمية الطعام',
          'How did we do?': 'كيف أبلينا؟',
          'communication': 'تواصل',
          'hygiene': 'صحة',
          "About required": "حول المطلوبة",
          'FeedBack': 'تعليق',
          'Skip': 'يتخطى',
          'Restaurants': 'مطاعم',
          'Layers of delicious restoring': 'طبقات من الترميم اللذيذ',
          'Up to \$10 Master card Cashback':
              'ما يصل إلى \$10 استرداد نقدي لبطاقة ماستر كارد',
          'Use code Card Above \$120': 'استخدم رمز البطاقة فوق \$120',
          'Select Date': 'حدد تاريخ',
          'Menu List': 'قائمة القائمة',
          'Slots not available': 'فتحات غير متوفرة',
          'Please select slot number': 'الرجاء تحديد رقم الفتحة',
          'Please select guest number': 'الرجاء تحديد رقم الضيف',
          'Lunch': 'غداء',
          'Dinner': 'عشاء',
          'Next': 'التالي',
          'Number Of Guests': 'عدد الضيوف',
          'We have max': 'لدينا كحد أقصى',
          'sitting capacity': 'قدرة الجلوس',
          'Select Your Offer': 'حدد العرض الخاص بك',
          'Off On “A La Carte” Menu': '“A La Carte” إيقاف في القائمة',
          'Discount available for the booked timeslot preset menus and drinks not included':
              'يتوفر الخصم على القوائم المحددة مسبقًا والمشروبات غير متضمنة',
          'off': 'عن',
          'No Offer Selected': 'لم يتم تحديد أي عرض',
          'Restaurants Menu Chosen For You': 'قائمة المطاعم المختارة لك',
          'Please select menu': 'الرجاء تحديد القائمة',
          'Dine In': 'تناول الطعام في',
        }
      };
}
